import time
import random
from dataclasses import dataclass
from typing import Tuple, Dict

# --- Configuration Constants ---
CRITICAL_TEMP_THRESHOLD = 80.0  # Degrees Celsius
WARNING_TEMP_THRESHOLD = 65.0   # Degrees Celsius
MAX_TX_POWER = 25.0             # dBm
MIN_TX_POWER = 10.0             # dBm
BASE_TX_POWER = 20.0            # dBm

@dataclass
class SystemStatus:
    """Data structure to hold the current snapshot of the system."""
    board_temp: float
    cpu_load: int
    fan_speed: int
    ambient_temp: float
    signal_interference: int
    tx_power: float
    state_description: str

class InternalSensors:
    """Simulates the internal physiological state of the hardware."""
    
    def __init__(self):
        self.board_temp = 50.0  # Starting temperature
        self.cpu_load = 10      # Idle load
        self.fan_speed = 30     # Idle fan speed (%)

    def update_physics(self, traffic_load: int, ambient_temp: float, current_tx_power: float, fan_cooling_effect: float):
        """
        Updates internal physics. 
        Note: Heat is generated by Traffic Load AND Transmission Power.
        """
        self.cpu_load = traffic_load
        
        # Heat Generation Logic:
        # 1. Base ambient heat
        # 2. Stress from CPU (Traffic)
        # 3. Stress from Radio (TX Power) - Higher power = More heat
        power_heat_factor = (current_tx_power / 10) 
        generated_heat = (traffic_load / 15) + power_heat_factor
        
        # Cooling Logic:
        cooling = (self.fan_speed / 100) * fan_cooling_effect
        
        # New Temperature Calculation with inertia (doesn't jump instantly)
        target_temp = ambient_temp + generated_heat - cooling + 10 # +10 is base operating offset
        
        # Smooth transition to target temp (simulation of thermal mass)
        self.board_temp = (self.board_temp * 0.7) + (target_temp * 0.3)
        self.board_temp = round(self.board_temp, 1)

    def set_fan_speed(self, speed: int):
        self.fan_speed = max(0, min(100, speed))

    def get_vitals(self) -> Dict[str, float]:
        return {"Temp": self.board_temp, "CPU": self.cpu_load, "Fan": self.fan_speed}

class ExternalSensors:
    """Simulates the external environment (Djelfa region climate)."""
    
    def scan_environment(self) -> Dict[str, float]:
        # Simulate a hot afternoon with intermittent wind gusts
        ambient_temp = 38 + random.uniform(-1, 2)
        
        # RSL Fluctuation (Negative values imply fading due to wind/dust)
        # Random burst of interference
        rsl_impact = random.choice([0, -0.5, -1, -4, -6]) 
        
        return {"Ambient_Temp": ambient_temp, "RSL_Impact": rsl_impact}

class SentientNode:
    """
    A self-aware network node that balances Service Quality (QoS) 
    against Self-Preservation (Survival).
    """
    
    def __init__(self):
        self.body = InternalSensors()
        self.eyes = ExternalSensors()
        self.tx_power = BASE_TX_POWER
        self.status_msg = "Initializing..."
    
    def _contemplate(self, vitals: Dict, env: Dict) -> Tuple[str, str, float, int]:
        """
        The Brain: Analyzes data and decides on a strategy.
        Returns: (Action Name, Reasoning, New TX Power, New Fan Speed)
        """
        temp = vitals['Temp']
        interference = env['RSL_Impact']
        
        # --- LOGIC LAYER ---
        
        # 1. SURVIVAL MODE (Priority: Hardware Safety)
        if temp >= CRITICAL_TEMP_THRESHOLD:
            return (
                "CRITICAL SURVIVAL PROTOCOL",
                f"Core temp ({temp}°C) critical. Risk of permanent damage. Dumping power load immediately.",
                MIN_TX_POWER, # Force drop power
                100           # Max fans
            )

        # 2. DEFENSIVE MODE (Priority: Prevent Overheating)
        # Situation: Hot hardware + Signal interference. 
        # Dilemma: Increasing power fixes signal but increases heat.
        # Decision: Do NOT increase power. Accept packet loss to save the board.
        elif temp >= WARNING_TEMP_THRESHOLD and interference < -2:
            return (
                "CONSERVATIVE RESISTANCE",
                f"Interference detected ({interference}dB), but temp is high ({temp}°C). Cannot boost power safely. Holding ground.",
                max(MIN_TX_POWER, self.tx_power - 1), # Slowly reduce power to cool down
                85 # High fans
            )

        # 3. AGGRESSIVE MODE (Priority: Signal Quality / ATPC)
        # Situation: Hardware is cool, but signal is bad.
        # Decision: Boost power to overcome interference.
        elif interference <= -3 and temp < WARNING_TEMP_THRESHOLD:
            target_power = min(MAX_TX_POWER, self.tx_power + 3)
            return (
                "ACTIVE COMPENSATION (ATPC)",
                f"Strong fading detected ({interference}dB). Thermal headroom available. Boosting TX Power.",
                target_power,
                60 # Moderate fans
            )

        # 4. OPTIMAL MODE (Priority: Efficiency)
        else:
            # Gradually return to base power if it was changed
            if self.tx_power > BASE_TX_POWER:
                new_power = self.tx_power - 1
            elif self.tx_power < BASE_TX_POWER:
                new_power = self.tx_power + 1
            else:
                new_power = BASE_TX_POWER
                
            return (
                "OPTIMAL OPERATION",
                "Conditions nominal. Maintaining efficiency.",
                new_power,
                40 # Low fans (Quiet mode)
            )

    def run_cycle(self, traffic_load: int):
        """Executes one simulation cycle: Sense -> Think -> Act"""
        
        # 1. SENSE (Gather Data)
        env_data = self.eyes.scan_environment()
        
        # Update physics based on PREVIOUS state's decisions (simulating reality)
        # Note: 15 is an arbitrary cooling coefficient for the simulation
        self.body.update_physics(traffic_load, env_data['Ambient_Temp'], self.tx_power, fan_cooling_effect=15)
        vitals = self.body.get_vitals()
        
        # 2. THINK (Contemplate)
        action, reason, new_power, new_fan = self._contemplate(vitals, env_data)
        
        # 3. ACT (Apply Decisions)
        self.tx_power = new_power
        self.body.set_fan_speed(new_fan)
        self.status_msg = action

        # 4. REPORT (Dashboard)
        self._log_status(vitals, env_data, reason)

    def _log_status(self, vitals, env, reason):
        print("\n" + "="*60)
        print(f"📡 SYSTEM CYCLE | Traffic Load: {vitals['CPU']}%")
        print("-" * 60)
        print(f"👁️  SENSORS  | Ambient: {env['Ambient_Temp']:.1f}°C | RSL Delta: {env['RSL_Impact']}dB")
        print(f"🫀  VITALS   | Board Temp: {vitals['Temp']}°C | Fan Speed: {vitals['Fan']}%")
        print("-" * 60)
        print(f"🧠  DECISION | {self.status_msg}")
        print(f"💬  THOUGHT  | \"{reason}\"")
        print(f"⚡  ACTION   | TX Power set to: {self.tx_power} dBm")
        print("="*60)

# --- Simulation Execution ---

if __name__ == "__main__":
    node = SentientNode()
    
    # Simulation Scenario:
    # 1. Morning (Low load)
    # 2. Noon (High load, heat rising)
    # 3. Sandstorm (High load, heat, signal loss)
    # 4. Cooling down (Load drops)
    
    traffic_pattern = [20, 50, 80, 95, 95, 95, 40, 20]
    
    print("🚀 STARTING SENTIENT NODE SIMULATION (DJELFA REGION PROFILE)...")
    time.sleep(1)

    for load in traffic_pattern:
        node.run_cycle(load)
        time.sleep(2) # Pause to let the user read